### ISSUE TITLE
Multiple Outcomes Monte Carlo

### ISSUE THREAD

**Issue by cactus911** [cactus911/momentForests#19]
Run a Monte Carlo with, say, 10 outcomes and a single treatment. Initially, we will not have any covariates.

We want to compare against the case where we also run 10 separate RCT evaluations on each outcome variable sequentially.

Try for several different sample sizes (250, 500, and 1000?).

**Comment by charliean942** [comment]
4 different simulations were run. The Stata simulation code, along with the summary of the results in excel files, is uploaded.
I will upload additional simulation results with different sample sizes.

**Comment by cactus911** [comment]
Thanks for this so far. A few things:

1. Please be more liberal and descriptive in your use of comments when committing things to Github. You should be very specific about what you are adding/changing, etc.

2. These results are a bit weird. How is it possible that the standard errors are larger for the grouped effects in the forest than in the separate regressions?

3. It would be useful to have an easier way to read all the results together. Please collate them into a single results document.

4. I have a few additional specifications that I'd like to see:
a. Please increase the variance of the error term equally for all outcomes.
b. Please set the true effect is 0 for half of the outcomes.
c. Please run a specification where the number of outcomes is equal to 50 instead of 10, with half of them true zero treatment effects.

**Comment by cactus911** [comment]
Implemented in the code base. Works, integrated with new memory management model, much faster, much larger sample sizes possible.
