### ISSUE TITLE
Moment Forest code is missing

### ISSUE THREAD

**Issue by cactus911** [cactus911/momentForests#2]
Currently, the code for generating a moment forest, and it associated utilities to extract information from it, is missing in the code base.

- [x] Inject moment forest wrapper codes into the core Java code.

**Comment by cactus911** [comment]
@charliean942 I believe that we have implemented this in the codebase, correct?

**Comment by charliean942** [comment]
> @charliean942 I believe that we have implemented this in the codebase, correct?
@cactus911 The code for generating a moment forest consists of java source codes, associated java utilities (jars), and a Stata ado file (a Stata file for programming). Users can modify the java source codes and Stata ado file for their own purposes. If this is what you mean by "codebase", the answer is yes.

**Comment by cactus911** [comment]
The question is whether or not we have brought the forest to the Github code. I believe we have, but I am verifying with you since I have not compiled and run this yet on my own machine. I want to close out these two issues if they are resolved.

**Comment by charliean942** [comment]
In that sense, I believe the issues (both forest and bootstrap) are resolved. You are supposed to be able to run this after compiling.

**Comment by cactus911** [comment]
In the code.
