### ISSUE TITLE
Bootstrapped standard errors are missing

### ISSUE THREAD

**Issue by cactus911** [cactus911/momentForests#3]
The current code base does not have the code for bootstrapping standard errors.

- [ ] Inject code to allow for bootstrapped standard errors in a random forest.

**Comment by cactus911** [comment]
@charliean942 This is also in the codebase now also?

**Comment by charliean942** [comment]
> @charliean942 This is also in the codebase now also?
@cactus911 The code for bootstrapping also consists of java source codes, associated java utilities (jars), and the same Stata ado file.

**Comment by cactus911** [comment]
In the code.
